### ISSUE TITLE
Doesn't work on 20.05

### ISSUE THREAD

**Issue by AndrewBWS** [bywatersolutions/koha-plugin-rolling-hard-due-dates#4] opened 2021-01-13 19:15 UTC
When I upload this plugin on a 20.05 install, it doesn't show in the list of installed plugins.

**Comment by kylemhall** [comment] 2021-01-15 16:13
I was not able to reproduce this on Koha v20.05.06

**Comment by tomascohen** [comment] 2021-03-29 13:23
Fixed on v1.0.7

**Closed as completed by tomascohen** 2021-03-29 13:23 UTC
